item {
    name: "Nasi putih"
    id: 1
}

item {
    name: "Nasi goreng"
    id: 2
}

item {
    name: "Capcay"
    id: 3
}

item {
    name: "Bihun goreng"
    id: 4
}

item {
    name: "Tahu goreng"
    id: 5
}

item {
    name: "Bakwan"
    id: 6
}

item {
    name: "Ayam"
    id: 7
}

item {
    name: "Tumis kangkung"
    id: 8
}

item {
    name: "Rendang"
    id: 9
}

item {
    name: "Tumis buncis"
    id: 10
}

item {
    name: "Gudeg"
    id: 11
}

item {
    name: "Kerupuk"
    id: 12
}

item {
    name: "Omelette"
    id: 13
}

item {
    name: "Tumis mie"
    id: 14
}

item {
    name: "Bakso goreng"
    id: 15
}

item {
    name: "Kentang mustofa"
    id: 16
}

item {
    name: "Nasi kuning"
    id: 17
}

item {
    name: "Nugget goreng"
    id: 18
}

item {
    name: "Pisang"
    id: 19
}

item {
    name: "Kentang balado"
    id: 20
}

item {
    name: "Telur balado"
    id: 21
}

item {
    name: "Telur ceplok"
    id: 22
}

item {
    name: "Telur dadar"
    id: 23
}

item {
    name: "Tempe goreng"
    id: 24
}

item {
    name: "Teri goreng"
    id: 25
}

item {
    name: "Tumis kacang panjang"
    id: 26
}

item {
    name: "Ayam asam manis"
    id: 27
}

item {
    name: "Ayam bakar"
    id: 28
}

item {
    name: "Ayam goreng"
    id: 29
}

item {
    name: "Ayam suwir"
    id: 30
}

item {
    name: "Jeruk"
    id: 31
}

item {
    name: "Tumis tempe"
    id: 32
}

item {
    name: "Lalapan"
    id: 33
}

item {
    name: "Opor ayam"
    id: 34
}

item {
    name: "Pecel"
    id: 35
}

item {
    name: "Perkedel"
    id: 36
}

item {
    name: "Sambal"
    id: 37
}

item {
    name: "Serundeng"
    id: 38
}

item {
    name: "Telur"
    id: 39
}

item {
    name: "Telur asin"
    id: 40
}

item {
    name: "Telur goreng"
    id: 41
}